# learn how to create functions and classes

#### create Functions

In [70]:
def function_name(x,y):
    return x,y

In [71]:
returned_value = function_name(3,5)

In [72]:
returned_value

(3, 5)

#### create classes

In [26]:
class class_name1():
    def __init__(self,d,b):
        self.d = d   
        self.b = b
    def laith(self,z):
        self.z = z
        
        return self.z + self.d + self.b
        

In [27]:
class class_name2(class_name1):
    
    def __init__(self,x,y):
        super().__init__(6,10)
        self.x = x        
        self.y = y
    def mohammed(self,z):
        self.z = z
        
        return self.z + self.x + self.y + self.d + self.b
        

In [28]:
values = class_name2(5,9)

In [29]:
values

In [35]:
values.laith(3)

19

In [31]:
values.mohammed(45)

75

## simple neural network 

#### input --------- [neural network] --------- output        (supervised)

In [36]:
import numpy as np

In [37]:
x = np.array([1,2,3,4])   # input
# y = 4.3*x - 2.2

y = np.array([2.1,6.4,10.7,15])  # output


In [39]:
# y = W.x + b     .... W = 4.3  /  b = -2.2

In [86]:
W = np.random.rand(1)   ## weight 
b = np.random.rand(1)   ## bias   

In [87]:
b

array([0.09333367])

# Feedword propagation

In [88]:
y_pred = W*x + b 

loss = np.mean((y_pred - y)**2)   #### (1/n) sum(( y-y_pred)^2)

In [89]:
y_pred

array([0.38983336, 0.68633305, 0.98283273, 1.27933242])

In [90]:
loss

79.5626796058917

# Backward Propagation

In [91]:
dy_pred = -2*(y-y_pred)
dW = np.dot(dy_pred,x)

db = np.mean(dy_pred)

W = W - 0.01*dW
b = b - 0.01*db

In [92]:
b

array([0.24764201])

In [93]:
def model(x,y,W,b):
    
    for i in range(50000):
        # forward
        y_pred = W*x + b 
        loss = np.mean((y_pred - y)**2)   #### (1/n) sum(( y-y_pred)^2)
        if i%10 == 0:
            #print(loss)
            pass
        # backward
        dy_pred = -2*(y-y_pred)
        dW = np.dot(dy_pred,x)

        db = np.mean(dy_pred)

        W = W - 0.01*dW
        b = b - 0.01*db
    
    print("the final weight : {} and bias : {}".format(W,b))
    return W,b

In [94]:
W, b = model(x,y,W,b)

the final weight : [4.3] and bias : [-2.2]


array([0.2010036])

In [84]:
y_pred = W*300 + b

In [85]:
y_pred

array([1287.8])